// Code generated by "stringer -type=Protocol"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeldonCoreV1-1]
	_ = x[SeldonCoreV1Alpha1-2]
	_ = x[SeldonCoreV1Alpha2-3]
}

const _Protocol_name = "SeldonCoreV1SeldonCoreV1Alpha1SeldonCoreV1Alpha2"

var _Protocol_index = [...]uint8{0, 12, 30, 48}

func (i Protocol) String() string {
	i -= 1
	if i < 0 || i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
